apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: csi-rclone-node
  namespace: system
spec:
  selector:
    matchLabels:
      app: csi-rclone-node
  template:
    spec:
      containers:
        - name: rclone
          args:
            - "-v=5"
            - "--nodeid=$(NODE_ID)"
            - "--endpoint=$(CSI_ENDPOINT)"
            - "--metrics-addr=:5572"
            - "--metrics-path=/metrics"
            - "--metrics-server-read-timeout=10s"
            - "--metrics-server-write-timeout=10s"
            - "--metrics-server-idle-timeout=60s"
          ports:
            - name: metrics
              containerPort: 5572
              protocol: TCP
