extends: default

rules:
  line-length:
    max: 120
    level: warning
  comments:
    min-spaces-from-content: 1
  truthy:
    allowed-values: ['true', 'false', 'on', 'off']
  indentation:
    spaces: 2
  key-duplicates: enable
  key-ordering: disable
  new-line-at-end-of-file: enable
  octal-values:
    forbid-implicit-octal: true
  quoted-strings:
    quote-type: single
    check-keys: false
