# Skaffold configuration for CSI Driver Rclone
#
# Quick Start:
#   skaffold dev                    # Default profile (no metrics, no RC)
#   skaffold dev -p metrics-full    # Full monitoring stack
#   skaffold dev -p rc-service      # RC API with Service
#
# Available Profiles:
#   default            - Basic CSI driver (no metrics, no RC)
#   metrics            - Metrics endpoint only
#   metrics-service    - Metrics + Service
#   metrics-prometheus - Metrics + Service + ServiceMonitor (requires Prometheus Operator)
#   metrics-dashboard  - Grafana Dashboard only
#   metrics-full       - Complete setup (Service + ServiceMonitor + Dashboard)
#   rc-basic           - RC API endpoint only (requires csi-rclone-rc-auth secret)
#   rc-service         - RC API + Service (requires csi-rclone-rc-auth secret)
#   mount-existing     - Mount existing volume mount points on startup
#
# Port Forwards:
#   metrics-service, metrics-prometheus, metrics-full:
#     - localhost:5572  → Metrics endpoint
#   metrics-prometheus, metrics-full:
#     - localhost:9090  → Prometheus UI
#   metrics-dashboard, metrics-full:
#     - localhost:3000  → Grafana UI (credentials: admin/prom-operator)
#   rc-service:
#     - localhost:5573  → RC API endpoint
#
# Prerequisites for RC profiles:
#   Create the RC auth secret before using RC profiles:
#   kubectl create secret generic csi-rclone-rc-auth \
#     --from-literal=username=admin \
#     --from-literal=password=secure-password \
#     -n veloxpack

apiVersion: skaffold/v4beta13
kind: Config
metadata:
  name: veloxpack

build:
  tagPolicy:
    customTemplate:
      template: "{{.IMAGE_NAME}}:latest"
  artifacts:
    - image: ghcr.io/veloxpack/csi-driver-rclone
      docker:
        dockerfile: Dockerfile
manifests:
  kustomize:
    paths:
      - deploy/overlays/default

profiles:
  # Default profile — no metrics
  - name: default
    manifests:
      kustomize:
        paths:
          - deploy/overlays/default

  # Basic metrics profile — enables metrics endpoint only (no Service, ServiceMonitor, or Dashboard)
  # Useful for manual scraping or custom metrics collection
  - name: metrics
    manifests:
      kustomize:
        paths:
          - deploy/overlays/metrics

  # Mount existing volume mount points on startup
  - name: mount-existing
    manifests:
      kustomize:
        paths:
          - deploy/overlays/mount-existing

  # Metrics with Service — adds Kubernetes Service for metrics endpoint
  # Useful for annotation-based Prometheus scraping or service discovery
  - name: metrics-service
    manifests:
      kustomize:
        paths:
          - deploy/overlays/metrics-service
    portForward:
      - resourceType: service
        resourceName: csi-rclone-node-metrics
        namespace: veloxpack
        port: 5572
        localPort: 5572

  # Metrics with Prometheus Operator — full Prometheus integration
  - name: metrics-prometheus
    manifests:
      kustomize:
        paths:
          - deploy/overlays/metrics-prometheus
    portForward:
      - resourceType: service
        resourceName: csi-rclone-node-metrics
        namespace: veloxpack
        port: 5572
        localPort: 5572
      - resourceType: service
        resourceName: kube-prometheus-stack-prometheus
        namespace: monitoring
        port: 9090
        localPort: 9090

  # Grafana Dashboard only — deploys only the dashboard ConfigMap
  # Note: Metrics must be enabled separately (use another profile or Helm)
  # Prerequisites: Grafana with sidecar watching for grafana_dashboard: "1" label
  - name: metrics-dashboard
    manifests:
      kustomize:
        paths:
          - deploy/overlays/metrics-dashboard
    portForward:
      - resourceType: service
        resourceName: kube-prometheus-stack-grafana
        namespace: monitoring
        port: 80
        localPort: 3000

  # Full monitoring stack — everything enabled
  # Prerequisites: kube-prometheus-stack installed with Grafana sidecar
  - name: metrics-full
    manifests:
      kustomize:
        paths:
          - deploy/overlays/metrics-full
    portForward:
      - resourceType: service
        resourceName: csi-rclone-node-metrics
        namespace: veloxpack
        port: 5572
        localPort: 5572
      - resourceType: service
        resourceName: kube-prometheus-stack-prometheus
        namespace: monitoring
        port: 9090
        localPort: 9090
      - resourceType: service
        resourceName: kube-prometheus-stack-grafana
        namespace: monitoring
        port: 80
        localPort: 3000

  # Basic RC API profile — enables RC API endpoint only (no Service)
  # Prerequisites: Create csi-rclone-rc-auth secret with username/password
  - name: rc-basic
    manifests:
      kustomize:
        paths:
          - deploy/overlays/rc-basic

  # RC API with Service — adds Kubernetes Service for RC API endpoint
  # Prerequisites: Create csi-rclone-rc-auth secret with username/password
  - name: rc-service
    manifests:
      kustomize:
        paths:
          - deploy/overlays/rc-service
    portForward:
      - resourceType: service
        resourceName: csi-rclone-node-rc
        namespace: veloxpack
        port: 5573
        localPort: 5573
