---
# Rclone CSI Driver - PersistentVolume Example
# This example demonstrates how to create a PersistentVolume with inline rclone configuration
apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/provisioned-by: rclone.csi.veloxpack.io
  name: pv-rclone-example
  namespace: default
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany  # Rclone supports ReadWriteMany for cloud storage
  persistentVolumeReclaimPolicy: Delete
  mountOptions:
    - debug-fuse
  csi:
    driver: rclone.csi.veloxpack.io
    volumeHandle: rclone-pv-example-volume
    volumeAttributes:
      remote: "s3"
      remotePath: "mybucket"
      # Inline rclone configuration for MinIO S3-compatible storage
      configData: |
        [s3]
        type = s3
        provider = Minio
        endpoint = http://minio.default.svc.cluster.local:9000
        access_key_id = admin
        secret_access_key = password
---
# PersistentVolumeClaim that references the above PV
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-rclone-example
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  volumeName: pv-rclone-example
  storageClassName: ""  # Empty string means no dynamic provisioning
---
# Example application pod using the rclone volume
apiVersion: v1
kind: Pod
metadata:
  name: rclone-test-app
  namespace: default
spec:
  containers:
    - image: nginx
      name: web-server
      ports:
        - containerPort: 80
          protocol: TCP
      resources:
        requests:
          cpu: 100m
          memory: 128Mi
        limits:
          cpu: 500m
          memory: 512Mi
      volumeMounts:
        - name: rclone-storage
          mountPath: /usr/share/nginx/html
          readOnly: false
      # Example: Create a test file to verify rclone mount works
      command: ["/bin/sh"]
      args: ["-c", "echo 'Hello from rclone CSI driver!' > /usr/share/nginx/html/index.html && nginx -g 'daemon off;'"]
  volumes:
    - name: rclone-storage
      persistentVolumeClaim:
        claimName: pvc-rclone-example
