---
apiVersion: v1
kind: Secret
metadata:
  name: rclone-secret
  namespace: default
type: Opaque
stringData:
  # Default remote configuration
  # These values can be overridden by volumeAttributes in PV/StorageClass
  remote: "s3"
  remotePath: "mybucket"
  configData: |
    [s3]
    type = s3
    provider = Minio
    endpoint = http://minio.default.svc.cluster.local:9000
    access_key_id = admin
    secret_access_key = password
---
apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/provisioned-by: rclone.csi.veloxpack.io
  name: pv-nginx
  namespace: default
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  csi:
    driver: rclone.csi.veloxpack.io
    volumeHandle: data-id
    nodePublishSecretRef:
      name: rclone-secret
      namespace: default
    # volumeAttributes:
    #   remote: "s3"
    #   remotePath: "mybucket"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-nginx
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  volumeName: pv-nginx
  storageClassName: ""
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-rclone-example
  namespace: default
spec:
  containers:
    - image: nginx
      name: nginx
      ports:
        - containerPort: 80
          protocol: TCP
      resources:
        requests:
          cpu: 100m
          memory: 128Mi
        limits:
          cpu: 500m
          memory: 512Mi
      volumeMounts:
        - name: pvc-nginx
          mountPath: /usr/share/nginx/html
          readOnly: false
  volumes:
    - name: pvc-nginx
      persistentVolumeClaim:
        claimName: pvc-nginx
